services:
  - type: web
    name: tiwari-platform
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn tiwari_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"
